Raw vanadium correction
neutrons/SNAPRed pull request #96
Opened 2023-08-24 15:37 UTC by rboston628

Work for [EWM780](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=780)

2023-09-20 17:34 UTC, darshdinger requested changes

2023-09-20 17:34 UTC, darshdinger commented on src/snapred/backend/recipe/algorithm/UnfocusedNormalizationCorrection.py
![image](https://github.com/neutrons/SNAPRed/assets/106342815/8c6db74b-ba0d-42f2-9190-7f8e25365797)
In testing this algo, I believe that this gives the correct output but I'm unsure of the issue found within the parameter sent to set the filename. It gives an error of file not being found but isn't this script supposed to produce an output correction file?

2023-09-20 17:36 UTC, darshdinger requested changes

2023-09-20 17:36 UTC, darshdinger commented on src/snapred/backend/recipe/algorithm/UnfocusedNormalizationCorrection.py
> +        self.rawVFile: str = stateConfig.rawVanadiumCorrectionFileName
Might be an issue here.

2023-09-20 17:41 UTC, darshdinger commented on src/snapred/backend/recipe/algorithm/UnfocusedNormalizationCorrection.py
> +        self.rawVFile: str = stateConfig.rawVanadiumCorrectionFileName
Okay, found it. This file is defined within src.tests.resources.inputs.ReductionParameters.json -> rawVCorrFileName. Unsure as to why this is being invoked at all.

2023-09-22 18:25 UTC, rboston628 commented on src/snapred/backend/recipe/algorithm/UnfocusedNormalizationCorrection.py
What did you run to create this error?

2023-09-27 17:08 UTC, darshdinger commented on src/snapred/backend/recipe/algorithm/UnfocusedNormalizationCorrection.py
Let me know if I'm missing something.

2023-09-27 17:51 UTC, mguthriem commented on src/snapred/backend/recipe/algorithm/UnfocusedNormalizationCorrection.py
something looks to be hardwired to look for the prototype output unfocused vanadium correction: "RVMB57573.lite.nxs". I don't know why this would be looked for, since the purpose of the algo is to create this file from scratch?

2023-10-02 14:48 UTC, darshdinger commented on src/snapred/backend/recipe/algorithm/UnfocusedNormalizationCorrection.py
^^^^^^^^^^Yep @rboston628 this is what I ran into as well^^^^^^^^^^

2023-10-10 19:25 UTC, rboston628 commented on src/snapred/backend/recipe/algorithm/UnfocusedNormalizationCorrection.py
"RVMB57573.lite.nxs" is coming from the `rawVanadiumCorrectionFilename` [inside the `StateConfig` DAO](https://github.com/neutrons/SNAPRed/blob/4a64ab88c67747fbf8e07ac56a23027862a5f9ea/src/snapred/backend/dao/StateConfig.py#L19).  From what I understood, this is supposed to be a background run performed under analogous circumstances as the data, and the purpose of this algorithm is to subtract off the background data represented by this file.

2023-10-10 21:55 UTC, mguthriem commented on src/snapred/backend/recipe/algorithm/UnfocusedNormalizationCorrection.py
`UnfocusedNormalizationCorrection` should be taking two input (raw neutron) calibration datasets (measured in a specific instrument state) and then using these to create a calibration dataset. It should also then save this calibration dataset to disk in the corresponding state calibration folder. 

In my prototype, I called these output files RVMB12345.nxs or RVM12345.lite.nxs (depending on lite mode), where 12345 was the run number of the input raw neutron dataset.

Subsequently, the RVMB file is loaded during reduction, is `DiffractionFocussed` (using exactly the same parameters as the sample data being reduced), `StripPeaksAndSmoothed` and, finally, used to *divide* the data.

This division normalizes for the fact that the total flux of neutrons generated (and measured) is different at different wavelengths.

2023-10-13 16:32 UTC, rboston628 commented
This PR was opened before the hackathon, and its commit history got badly polluted since then.  I'm going to close and reopen a cleaner branch.

2023-10-13 16:32 UTC, closed without merging